# Generated by Django 5.2 on 2025-05-01 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='image',
            field=models.ImageField(null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='statue',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('cancelled', 'Cancelled'), ('postponed', 'Postponed'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=100),
        ),
    ]
