# Generated by Django 5.2 on 2025-05-01 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenment', '0002_alter_evenement_image_alter_evenement_statue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='statue',
            field=models.CharField(choices=[('draft', 'Draft'), ('cancelled', 'Cancelled'), ('onhold', 'OnHold'), ('confirmed', 'Confiremed')], default='draft', max_length=100),
        ),
    ]
